### ISSUE TITLE
Doesn't work with db update

### ISSUE THREAD

**Issue by hannesfant** [Hrdtr/nuxt-appwrite#281]
Appwrite updated the way they handle databases a while ago, it looks like that update broke this module. The module sends a request to `http://appwrite/v1/database/collections/COLLECTIONID/documents/DOCUMENTID` when in reality it should be `http://appwrite/v1/databases/DATABASEID/collections/COLLECTIONID/documents/DOCUMENTID`
More info about this here: https://appwrite.io/docs/client/databases?sdk=web-default#databasesUpdateDocument

I'm pretty sure you just need to update the appwrite package to the latest 9.x version

**Comment by Hrdtr** [comment]
Please use more up to date module:
https://github.com/YsarocK/nuxt-appwrite
