### ISSUE TITLE
Made a Nuxt 3 package, possible to switch the npm name ?

### ISSUE THREAD

**Issue by YsarocK** [Hrdtr/nuxt-appwrite#358]
Hi! #211
Built the nuxt3-appwrite package, was wondering if you could think about switching package name ? So that it could be referenced in nuxt modules ?
Could be usefull for Nuxt 3 users :/
Thanks for your work that has been a base for my package.

**Comment by YsarocK** [comment]
If you're struggling, check nuxt3-appwrite. Give it a try and reach at me if you have issue(s) or features request 🙏

**Comment by Hrdtr** [comment]
first of all, this is not how it works oss. why don't you fork this repo if you said this is the base of your code? for the record, I also said on discord if anyone has free time to modify the code to support nuxt3 please contribute to this repo, or fork it.

**Comment by YsarocK** [comment]
Ofc this is not. This is exactly why I tried to contact you (mail, Twitter, not only here). Would be a pleasure to collaborate.

But yeah, it needed a rework in order to be Nuxt3-compatible.
